# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nengyuan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nengyuan

  target 'NengyuanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NengyuanUITests' do
    inherit! :search_paths
    # Pods for testing
  end


      pod "AFNetworking"
      pod "Reachability"
      pod "MJExtension"
      pod "SDWebImage"
      pod "TPKeyboardAvoiding"  
      pod "MBProgressHUD"
      pod "MJRefresh"
      pod "Masonry"
      pod 'MJExtension'
      pod 'PGDatePicker'  #年月日历

end
